version: "3"
services:
  app:
      build:
        context: .
        dockerfile: ./app/Dockerfile
      
  db:
      image: mysql:5.6
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: 123456
      ports:
        - "8800:3306"
      volumes:
        - "./mysql-data:/var/lib/mysql"
      
  web:
      image: nginx:latest
      depends_on:
        - "db"
        - "app"
      ports:
          - "8888:80"
      volumes:
          - ./code:/code
          - ./site.conf:/etc/nginx/conf.d/000_site.conf
      links:
        - "db"
        - "app"
      

